# Generated by Django 3.2.4 on 2021-06-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userBalance_API', '0002_alter_userinfo_useraccountid'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferAmount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userBalance_API.userinfo')),
            ],
        ),
    ]
