# Generated by Django 3.2.4 on 2021-06-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userBalance_API', '0002_alter_userinfo_useraccountid'),
        ('userTransfer_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='userBalance_API.userinfo'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='senderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='userBalance_API.userinfo'),
        ),
    ]
