# Generated by Django 3.2.4 on 2021-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('userAccountID', models.IntegerField(max_length=20)),
                ('userAccountBalance', models.FloatField()),
            ],
        ),
    ]
