# Generated by Django 3.2.4 on 2021-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBalance_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userAccountID',
            field=models.IntegerField(),
        ),
    ]
